describe('Register', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[data-test="signup"]').click()
    cy.get('#firstName').type('Pedro')
    cy.get('#lastName').type('Araujo')
    cy.get('#username').type('PedroAra')
    cy.get('#password').type('123456')
    cy.get('#confirmPassword').type('123456')
    cy.get('[data-test="signup-submit"]').click()
    cy.get('#username').type('PedroAra')
    cy.get('#password').type('123456')
    cy.get('[data-test="signin-submit"]').click()
    cy.get('[data-test="user-onboarding-dialog-title"]')
    cy.get('[data-test="user-onboarding-next"]').click()
    cy.get('#bankaccount-bankName-input').type('NuTest')
    cy.get('#bankaccount-routingNumber-input').type('123456789')
    cy.get('#bankaccount-accountNumber-input').type('123456789')
    cy.get('[data-test="bankaccount-submit"]').click()
    cy.get('[data-test="user-onboarding-dialog-title"]')
    cy.get('[data-test="user-onboarding-next"]').click()
    cy.get('[data-test="user-onboarding-next"]')
    cy.get('[data-test="nav-contacts-tab"]')
    cy.get('[data-test="nav-personal-tab"]')
  })
})
